### ISSUE TITLE
Publish to crates.io ?

### ISSUE THREAD

**Issue by Nadrieril** [duesee/abnf#1]
Hey ! I've been using your crate in my https://github.com/Nadrieril/dhall-rust project, and now that I'm planning to publish it to crates.io, I'll need all dependant crates to be published as well.

So, would you mind if I published your crate there myself ? Or if you'd rather do it yourself, could you do it ?

**Comment by duesee** [comment]
Here you go https://crates.io/crates/abnf :-)

**Comment by Nadrieril** [comment]
Thank you very much !
