### ISSUE TITLE
Allow more characters in comments ?

### ISSUE THREAD

**Issue by Nadrieril** [duesee/abnf#11]
I have the following rule:
```abnf
forall                = %x2200 / %x66.6f.72.61.6c.6c ; "∀" / "forall"
```
Currently the comment makes a parse error because it contains a character outside the range `'\x21'..='\x7E'`. This is however very useful for rules that need to match non-ASCII characters.
Could this be allowed ?

PS: amazing job on the recent versions ! Thank you.

**Comment by duesee** [comment]
Yes, it would improve the parser. I wanted to ask you for a patch, but found that it is very easy to do, so I did it myself. See 8dd326f782c8897faec120f3d5dbb230f0d695f8. Does it work for you?

Thank you for the kind words! :-)

**Comment by Nadrieril** [comment]
> Does it work for you ?

Not quite, now it fails on my grammar even without any unicode.
I reduced it to the following:
```abnf
foo = "a" ; a comment
    / "b"
```
I get the following error:
```
0: at line 1, in Eof:
    / "b"
 ^
```

**Comment by duesee** [comment]
Oops, I thought the tests should cover it... do you have a trailing newline?

**Comment by Nadrieril** [comment]
I do

**Comment by Nadrieril** [comment]
My guess is that `take_until` doesn't consume the newline, but the previous code did

**Comment by duesee** [comment]
Good catch! f615bb93e87ad323a184524ad437f391d080cfbd

**Comment by duesee** [comment]
Btw, I do not want to steal your commits. If you are familiar with the code and can do it yourself, please say/do so! :-)

**Comment by Nadrieril** [comment]
Yay, that fixed it thanks !

> Btw, I do not want to steal your commits. If you are familiar with the code and can do it yourself, please say/do so! :-)

I'm actually not familiar with the code at all ^^ I just made an educated guess based on the diff of https://github.com/duesee/abnf/commit/8dd326f782c8897faec120f3d5dbb230f0d695f8.
