### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by colstrom** [duesee/abnf#16]
I'm not sure which license this crate uses. `Cargo.toml` indicates `AGPL-3.0`, but `README.md` indicates dual licensing under `Apache-2.0` AND `MIT`.

Confirmation one way or the other would be appreciated.

Thanks!

**Comment by duesee** [comment]
Oops, fixed in a72fd2e706664ef9e02333288819d3626f90d0b9 :-) "MIT OR Apache-2.0" it is. Thanks!

**Comment by duesee** [comment]
I pushed another commit (eaf52919ec8df492ec9a894f810ca5f633ce605b) to clarify the README, too. I am not entirely sure what the difference between "MIT AND APACHE" vs "MIT OR APACHE" is, but it seems that many other crates with a permissive license chose the "OR"-variant. I just did the same. If you have more experience here, please tell me if this is a proper choice for 1) keeping patent trolls away 2) being permissive, and 3) being compatible with GPL 2.0! :-)

**Comment by colstrom** [comment]
My understanding is that `MIT OR Apache-2.0` means "whichever you prefer", and `MIT AND Apache-2.0` means "both apply", usually in cases where some portions are released under only one of those licenses. I imagine that to be less common with this particular combination, but in a case like `BSD-2-Clause AND MPL-2.0` or something, where the MPL-2.0 is effectively a copyleft license that applies on a per-file basis, you could have *some* code that must remain under that license, while the rest could be licensed more permissively.

As far as the objectives you described there, I think `MIT OR Apache-2.0` meets your criteria. If someone wants/needs the patent grant (and termination conditions), they would choose the Apache option. If they don't, they'd probably choose the MIT option (which doesn't really deal with patent rights at all, either in terms of grants or revocation).

That said, I am very much not a lawyer. This is just my understanding of how things work.

Thank you very much for the quick response.
